login/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='login'

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^login/$',auth_views.login,{'template_name': 'registration/user_login.html'},name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^portal/$',views.portal,name='portal'),
    url(r'^portal/home/$',views.profile_home_page,name='portal_home'),
    url(r'^portal_form/home/$', views.profile_home, name='portal_form_home'),
    url(r'^portal_form/teaching/$',views.Teaching,name='portal_form_teaching'),
    url(r'^portal/teaching/$', views.Teaching_page, name='portal_teaching'),
    url(r'^portal_form/project/$', views.Project, name='portal_form_project'),
    url(r'^portal/project/$', views.Project_page, name='portal_project'),
    url(r'^portal_form/publication/$', views.Publication, name='portal_form_publication'),
    url(r'^portal/publication/$', views.Publication_page, name='portal_publication'),
    url(r'^portal_form/experience/$', views.Experience, name='portal_form_experience'),
    url(r'^portal/experience/$', views.Experience_page, name='portal_experience'),
    url(r'^portal_form/qualification/$', views.Qualification, name='portal_form_qualification'),
    url(r'^portal/qualification/$', views.Qualification_page, name='portal_qualification'),
    url(r'^fac_home/(?P<username>\w+)/$',views.fac_home, name="fac_home"),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password_reset/complete/$', auth_views.password_reset_complete,name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from login import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('login.urls', namespace="home")),
    # url(r'^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.decorators import login_required
from django.views  import generic
import datetime

# Create your models here

class signup(models.Model):
    username = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    album_logo = models.FileField()


    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User)
    webmail = models.CharField(max_length=200,default='')
    Faculty_name=models.CharField(max_length=300,default='')
    Department = models.CharField(max_length=300,default='')
    Academic_position = models.CharField(max_length=300,default='')
    Phone = models.IntegerField(default=0)
    RoomNo = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to='profile_image/',blank=True,default='media/profile_image/400x400.png')
    About = models.CharField(max_length=2000)
    linkedin = models.CharField(max_length=300,default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)



class Qualification(models.Model):
    user = models.OneToOneField(User)
    Undergraduate = models.CharField(max_length=300,default='')
    Postgraduate = models.CharField(max_length=300,default='')
    Phd = models.CharField(max_length=300,default='')
    Undergraduate_college=models.CharField(max_length=300,default='')
    Postgraduate_college = models.CharField(max_length=300, default='')
    Phd_college=models.CharField(max_length=300,default='')
    Undergraduate_year = models.IntegerField(default=0)
    Postgraduate_year = models.IntegerField(default=0)
    Phd_year=models.IntegerField(default=0)


    def __str__(self):
        return self.user.username


def create_qualification(sender, **kwargs):
    if kwargs['created']:
        user_qualification = Qualification.objects.create(user=kwargs['instance'])

post_save.connect(create_qualification, sender=User)

class Teaching(models.Model):
    user = models.ForeignKey(User)
    status = models.CharField(max_length=100,default='')
    year = models.CharField(max_length=200,default='')
    semester = models.CharField(max_length=200,default='')
    Course_name = models.CharField(max_length=100,default='')

    def __str__(self):
        return self.user.username




class Project(models.Model):
    user = models.ForeignKey(User)
    Title = models.CharField(max_length=500,default='')
    Sponser = models.CharField(max_length=300,default='')
    start_year = models.CharField(max_length=200,default='')
    end_year = models.CharField(max_length=200,default='')
    Role = models.CharField(max_length=500,default='')
    Description=models.CharField(max_length=2000,default='')

    def __str__(self):
        return self.user.username



class Publication(models.Model):
    user = models.ForeignKey(User)
    Type = models.CharField(max_length=300,default='')
    Title = models.CharField(max_length=300,default='')
    Description = models.CharField(max_length=1000,default='')


    def __str__(self):
        return self.user.username





class Experience(models.Model):
    user = models.ForeignKey(User)
    start_year = models.CharField(max_length=100,default='')
    end_year = models.CharField(max_length=100,default='')
    About = models.CharField(max_length=1000,default='')
    Responsibility = models.CharField(max_length=1000,default='')

    def __str__(self):
        return self.user.username

login/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import signup


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

    def __init__(self, *args, **kwargs):
        super(UserForm,self).__init__(*args, **kwargs)
        self.fields['password'].widget.attrs['placeholder'] = ('Password')

        for field_name in self.fields:
            field = self.fields.get(field_name)
            field.widget.attrs['placeholder'] = field.label
            field.label = ''

login/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required
from django.http import  HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import Profile,Qualification
from django.db import models
from . import models
from django.contrib.auth.models import User


def index(request):
    return redirect('profile/')
# Create your views here.


# def login(request):
#     next = request.GET.get('next', '/home')
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(username=username, password=paasword)
#
#         if user is not None:
#             if user.is_active:
#                 login(request,user)
#                 return HttpResponseRedirect(next)
#             else:
#                 return HttpResponse("inactive user")
#         else:
#             return render(request,"login/login.html", {'redirect_to:next'})




class UserFormView(View):
    form_class=UserForm
    template_name='registration/user_signup.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            user=form.save(commit=False)

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user=authenticate(username=username,password=password, email=form.cleaned_data['email'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('login:index')
            return render(request,self.template_name,{'form':form})


def profile(request):
    return render(request, 'registration/faculty_home.html')



def portal(request):
    return render(request, 'registration/signup.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/home/login')


# portal views starts from here


def profile_home_page(request):
    if not request.user.is_authenticated():
        return redirect('login')
    return render(request,'login/portal_home.html')



def profile_home(request):
    if not request.user.is_authenticated():
        return redirect('login')
    else:
        user=request.user
        Faculty_name = request.POST['Faculty_name']
        webmail = request.POST['webmail']
        Department = request.POST['Department']
        Academic_position = request.POST['Academic_position']
        Phone = request.POST['Phone']
        RoomNo = request.POST['RoomNo']
        About = request.POST['About']
        linkedin = request.POST['linkedin']
        profile_pic= request.FILES.get('profile_pic','profile_image/400x400.png')
        fac = models.Profile.objects.filter(user=request.user)
        if not fac.exists():
            faculty = models.Profile(Faculty_name=Faculty_name,webmail=webmail,Department=Department,Academic_position=Academic_position,
                                     Phone=Phone,RoomNo=RoomNo,About=About,linkedin=linkedin,profile_pic=profile_pic,)
            faculty.user=request.user
            faculty.save()
        else:
            models.Profile.objects.filter(user=user).update(Faculty_name=Faculty_name,webmail=webmail,Department=Department,
                                                            Academic_position=Academic_position,Phone=Phone,RoomNo=RoomNo,About=About,linkedin=linkedin,profile_pic=profile_pic,)
            fac = models.Profile.objects.get(user=user)
            fac.profile_pic = profile_pic
            fac.save()

        #     Faculty_name=Faculty_name,
        #     Department=Department,
        #     Academic_position=Academic_position,
        #     Phone=Phone,
        #     RoomNo=RoomNo,
        #     linkedin=linkedin,
        #     About=About,
        #     webmail=webmail,
        #     profile_pic=profile_pic,
        # )
        return HttpResponseRedirect('/home/')




def Qualification_page(request):
    if not request.user.is_authenticated():
        return redirect('login')
    return render(request, 'login/portal_qualification.html')


def Qualification(request):
    if not request.user.is_authenticated():
        return redirect('login')
    else:
        Undergraduate = request.POST['Undergraduate']
        Undergraduate_college = request.POST['Undergraduate_college']
        Undergraduate_year = request.POST['Undergraduate_year']
        Postgraduate = request.POST['Postgraduate']
        Postgraduate_college = request.POST['Postgraduate_college']
        Postgraduate_year = request.POST['Postgraduate_year']
        Phd = request.POST['Phd']
        Phd_college=request.POST['Phd_college']
        Phd_year = request.POST['Phd_year']
        models.Qualification.objects.filter(user=request.user).update(
            Undergraduate = Undergraduate,
            Undergraduate_college=Undergraduate_college,
            Undergraduate_year=Undergraduate_year,
            Postgraduate = Postgraduate,
            Postgraduate_college=Postgraduate_college,
            Postgraduate_year=Postgraduate_year,
            Phd = Phd,
            Phd_college=Phd_college,
            Phd_year=Phd_year,

        )
    return HttpResponseRedirect('/home')



def Teaching_page(request):
    if not request.user.is_authenticated():
        return redirect('login')
    return render(request,'login/portal_teaching.html')



def Teaching(request):
    if not request.user.is_authenticated():
        return redirect('login')
    else:
        year = request.POST['year']
        semester = request.POST['semester']
        status=request.POST['status']
        Course_name = request.POST['Course_name']
      # /*  models.Teaching.objects.filter(user=request.user).append(
      #       year=year,
      #       semester=semester,
      #       Course_name=Course_name,
      #   )
        obj = models.Teaching( year=year , semester = semester , Course_name=Course_name,status=status)
        obj.user = request.user
        obj.save()
        return HttpResponseRedirect('/home/')



def Project_page(request):
    if not request.user.is_authenticated():
        return redirect('login')
    return render(request,'login/portal_project.html')



def Project(request):
    if not request.user.is_authenticated():
        return redirect('login')
    else:
        Title = request.POST['Title']
        Sponser = request.POST['Sponser']
        start_year = request.POST['start_year']
        end_year = request.POST['end_year']
        Role = request.POST['Role']
        Description = request.POST['Description']
        # models.Project.objects.filter(user=request.user).update(
        #     Title=Title,
        #     Sponser = Sponser,
        #     start_year = start_year,
        #     end_year = end_year,
        #     Role = Role,
        #     Description=Description,
        # )
        obj = models.Project(Title=Title , Sponser=Sponser,start_year=start_year,end_year=end_year,Role=Role,Description=Description)
        obj.user = request.user
        obj.save()
        return HttpResponseRedirect('/home/')



def Publication_page(request):
    if not request.user.is_authenticated():
        return redirect('login')
    return render(request,'login/portal_publication.html')


def Publication(request):
    if not request.user.is_authenticated():
        return redirect('login')
    else:
        Type = request.POST['Type']
        Title = request.POST['Title']
        Description = request.POST['Description']
        # models.Publication.objects.filter(user=request.user).update(
        #     Type=Type,
        #     Title=Title,
        #     Description=Description,
        # )
        obj = models.Publication( Type=Type, Title=Title, Description=Description)
        obj.user =  request.user
        obj.save()
        return HttpResponseRedirect('/home')


def Experience_page(request):
    if not request.user.is_authenticated():
        return redirect('login')
    return render(request,'login/portal_experience.html')

def Experience(request):
    if not request.user.is_authenticated():
        return redirect('login')
    else:
        start_year = request.POST['start_year']
        end_year = request.POST['end_year']
        About = request.POST['About']
        Responsibility = request.POST['Responsibility']

        obj = models.Experience(start_year=start_year, end_year=end_year, About=About, Responsibility=Responsibility)
        obj.user= request.user
        obj.save()
        return HttpResponseRedirect('/home')


# fac profile can be seen from here

def fac_home(request,username):
    # faculty = get_object_or_404(User,email = email)
    # obj2 = Qualification.objects.all()
    #obj2= Qualification.objects.filter(user=faculty )
    user = User.objects.get(username=username )
    return render(request,'registration/faculty_home.html',{'user' : user})

login/templates/login/faculty_home.html
<html>

<!--{{ user.profile.Department }}-->
<!--{{ user.profile.Faculty_name }}-->
{{ user.qualification.Undergraduate }}
{{ user.id }}
{{ user.profile.profile_pic.url }}


<tbody>{% for field in user.teaching_set.all|dictsort:"year" %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ field.year }}</td>
        <td>{{ field.semester }}</td>
        <td> {{ field.Course_name }}</td><br>
    </tr>
    {% endfor %}
</tbody>
</html>

login/templates/login/index.html
<!DOCTYPE html>

<html >
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" 
	integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <head>
    <meta charset="UTF-8">

	
    <title>Random Login Form</title>
    
    {% load staticfiles %}
    
    
        <style>
        @import url(https://fonts.googleapis.com/css?family=Tenor+Sans);
      @import url(http://fonts.googleapis.com/css?family=Exo:100,200,400);
@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

body{
	margin: 0;
	padding: 0;
	background: #fff;

	color: #fff;
	font-family: Arial;
	font-size: 12px;
}

.body{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background-image:url({% static 'login/b.jpg' %});
background-position:30% 52%;
	background-repeat:no-repeat;
	background-color: #5D92BA;
	
	z-index: 0;
}

.grad{
	position: relative;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
	z-index: 1;
	opacity: 0.7;
}

.header{
	position: relative;
	margin-left:20%;
	margin-top:5%;
	z-index: 2;
	
}

.header div{
	float: left;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 35px;
	font-weight: 200;
}

.header div span{
	color: #5379fa !important;
}

#login , #signup{
	position: relative;
	display:inline-block;
	margin-left:50%;
	z-index:2;
}

#login input[type=text],  #signup input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
}

#login [type=password] ,#signup input[type=password]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
	margin-top: 10px;
}

#login  input[type=button],#signup input[type=button]{
	width: 250px;
	height: 35px;
	background: #fff;
	border: 1px solid #fff;
	cursor: pointer;
	border-radius: 2px;
	color: #a18d6c;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 6px;
	margin-top: 10px;
}

#login input[type=button]:hover ,#signup input[type=button]:hover{
	opacity: 0.8;
}

#login input[type=button]:hover ,#signup input[type=button]:active{
	opacity: 0.6;
}

#login input[type=text]:focus,#signup input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

#login input[type=password]:focus,#signup  input[type=password]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

#login input[type=button]:focus,#signup input[type=button]:focus{
	outline: none;
}

::-webkit-input-placeholder{
   color: rgba(255,255,255,0.6);
}

::-moz-input-placeholder{
   color: rgba(255,255,255,0.6);
   
}

.logo{
	position:relative;
	z-index:1;
	margin-top:50px;
	margin-left:50px;

}

.heading{
	
  	color: white;
	position:absolute;;
	z-index:1;
	margin-top:50px;
	margin-left:200px;
	
}

#signup{
		display:none;
}

    </style>

    
        <script src="js/prefixfree.min.js"></script>


  </head>

  <body>
  <div class="heading">
  	<h2 style="font-family: 'Exo', sans-serif;" >Indian Institute of Technology</h2><h2 style="font-family: 'Exo', sans-serif;">Guwahati</h2>
  	</div>
	<img class="logo" src="{% static 'login/a.jpg' %}">
    <div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Login/SignUp<span> Here..</span></div>
		</div>
		<br>
		<div id="login">
				<input type="text" placeholder="username" name="user"><br>
				<input type="password" placeholder="password" name="password"><br>
				<input type="button" value="Login"><br><br>
				<a  style="font-size:12px">Register Here</a>
				<button onclick="myfn()" type="button" class="btn btn-primary">SignUp</button>
		
		</div>
		<br> 
		<div id="signup">
				<form role="form" action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
					 {% include 'login/form-template.html' %}
				<!--<input type="text" placeholder="First Name" name="firstname"><br><br>-->
				<!--<input type="text" placeholder="Last Name" name="lastname"><br>-->
				<!--<input type="password" placeholder="password" name="password"><br>-->
				<button type="submit" >Submit</button>
					</form><br><br>
				<a style="font-size:12px">Login Here</a>
				<button onclick="myfn()" type="button" class="btn btn-primary">Login</button>

		</div>
   

    <script>
	function myfn() {
    var x = document.getElementById("login");
    var y = document.getElementById("signup");
    if (x.style.display === "none" || y.style.display === "block") {
        x.style.display = "block";
         y.style.display = "none";
    }
    else{
        x.style.display = "none";
         y.style.display = "block";
    }
}
</script>
    
    
    
  </body>
</html>

login/templates/login/login.html
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

login/templates/login/portal_experience.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

	
        <title>Startmin - Bootstrap Admin Theme</title>
        {% load static %}
        <!-- Bootstrap Core CSS -->
        <link href="{% static 'login/bootstrap.min_portal.css' %}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{% static 'login/metisMenu.min_portal.css' %}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{% static 'login/startmin_portal.css' %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'login/font-awesome.min_portal.css' %}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
             <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.html">Startmin</a>
                </div>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

               
                <ul class="nav navbar-right navbar-top-links">
                    <li class="dropdown navbar-inverse">
                        
                             <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="#">
                                    <div>
                                        
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                       
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div>
                                        
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a class="text-center" href="#">
                                   
                                   
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                             {{ user }} <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"> User Profile</a>
                            </li>
                         
                            <li class="divider"></li>
                            <li><a href="{% url 'login:logout' %}"> Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- /.navbar-top-links -->

                      <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                </span>
                                </div>
                                <!-- /input-group -->
                            </li>
                             <li>
                                        <a  href="{% url 'login:portal_home' %} ">Home</a>
                                    </li>
                            <li>
                                <a href="{% url 'login:portal_qualification' %}" >Qualifications</a>
                            </li>
                                          
                                 <li>
                                <a href="{% url 'login:portal_teaching' %}" >Teachings</a>
                            </li>
                            <li>
                                  <a href="{% url 'login:portal_publication' %}">Publications</a>
                            </li>
                             <li>
                                <a href="{% url 'login:portal_project' %}" > Projects</a>
                                <!-- /.nav-second-level -->
                            </li>
                             <li>
                                        <a href="{% url 'login:portal_experience' %}">Experience</a>
                                    </li>
                            <li>
                              
            </nav>
            <div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Works and Experience</h1>
                        <div class="form-group">
                            <form method="post" action="/home/portal_form/experience/" id="portal_experience" name="portal_experience"><br>
                                    {% csrf_token %}

                                                <label>Start year</label>
                                                <input class="form-control" placeholder="Start year" id="start_year" name="start_year"><br>
                                                <label>End Year</label>
                                                <input class="form-control" placeholder="End year" id="end_year" name="end_year"><br>
                                                <label>Responsibility</label>
                                                <input class="form-control" placeholder="Your role" id="Responsibility" name="Responsibility"><br>
                                                <label>About</label>
                                                <textarea class="form-control" rows="3" placeholder="Say something about your experience..." id="About" name="About"></textarea><br>

                                            <button type="submit" class="btn btn-default" form="portal_experience">Submit</button>
                            </form><br>
                                            <button type="reset" class="btn btn-default">Reset</button>

                        </div>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{% static 'login/jquery.min_portal.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'login/bootstrap.min_portal.js' %}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{% static 'login/metisMenu.min_portal.js' %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static 'login/startmin_portal.js' %}"></script>

    </body>
</html>